use logicrs::fol::FolOp;

#[repr(u32)]
#[allow(unused)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum BitwuzlaOp {
    Constant,
    ConstArray,
    Value,
    Variable,
    And,
    Distinct,
    Equal,
    Iff,
    Implies,
    Not,
    Or,
    Xor,
    Ite,
    Exists,
    Forall,
    Apply,
    Lambda,
    ArraySelect,
    ArrayStore,
    BvAdd,
    BvAnd,
    BvAshr,
    BvComp,
    BvConcat,
    BvDec,
    BvInc,
    BvMul,
    BvNand,
    BvNeg,
    BvNegOverflow,
    BvNor,
    BvNot,
    BvOr,
    BvRedand,
    BvRedor,
    BvRedxor,
    BvRol,
    BvRor,
    BvSaddOverflow,
    BvSdivOverflow,
    BvSdiv,
    BvSge,
    BvSgt,
    BvShl,
    BvShr,
    BvSle,
    BvSlt,
    BvSmod,
    BvSmulOverflow,
    BvSrem,
    BvSsubOverflow,
    BvSub,
    BvUaddOverflow,
    BvUdiv,
    BvUge,
    BvUgt,
    BvUle,
    BvUlt,
    BvUmulOverflow,
    BvUrem,
    BvUsubOverflow,
    BvXnor,
    BvXor,
    BvExtract,
    BvRepeat,
    BvRoli,
    BvRori,
    BvSignExtend,
    BvZeroExtend,
}

impl From<FolOp> for BitwuzlaOp {
    #[inline]
    fn from(op: FolOp) -> Self {
        match op {
            FolOp::Add => BitwuzlaOp::BvAdd,
            FolOp::Sub => BitwuzlaOp::BvSub,
            FolOp::Mul => BitwuzlaOp::BvMul,
            FolOp::Udiv => BitwuzlaOp::BvUdiv,
            FolOp::Sdiv => BitwuzlaOp::BvSdiv,
            FolOp::Urem => BitwuzlaOp::BvUrem,
            FolOp::Srem => BitwuzlaOp::BvSrem,
            FolOp::Eq => BitwuzlaOp::Equal,
            FolOp::Neq => BitwuzlaOp::Distinct,
            FolOp::Not => BitwuzlaOp::BvNot,
            FolOp::And => BitwuzlaOp::BvAnd,
            FolOp::Or => BitwuzlaOp::BvOr,
            FolOp::Xor => BitwuzlaOp::BvXor,
            FolOp::Implies => BitwuzlaOp::Implies,
            FolOp::Ite => BitwuzlaOp::Ite,
            FolOp::Ult => BitwuzlaOp::BvUlt,
            FolOp::Ugt => BitwuzlaOp::BvUgt,
            FolOp::Slt => BitwuzlaOp::BvSlt,
            FolOp::Sgt => BitwuzlaOp::BvSgt,
            FolOp::Concat => BitwuzlaOp::BvConcat,
            FolOp::Sll => BitwuzlaOp::BvShl,
            FolOp::Srl => BitwuzlaOp::BvShr,
            FolOp::Sra => BitwuzlaOp::BvAshr,
            FolOp::Sext => BitwuzlaOp::BvSignExtend,
            FolOp::Uext => BitwuzlaOp::BvZeroExtend,
            FolOp::Rol => BitwuzlaOp::BvRol,
            FolOp::Ror => BitwuzlaOp::BvRor,
            FolOp::Redxor => BitwuzlaOp::BvRedxor,
            FolOp::Neg => BitwuzlaOp::BvNeg,
            FolOp::Smod => BitwuzlaOp::BvSmod,
            op => panic!("unsupport op {op}"),
        }
    }
}
